replicaCount: 1

image:
  repository: ghcr.io/atlantisaj/task6-html-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

imagePullSecrets:
  - name: ghcr-creds
