apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-6
  template:
    metadata:
      labels:
        app: task-6
    spec:
      containers:
        - name: task-6
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
