apiVersion: apps/v1
kind: Deployment
metadata:
  name: task6-html-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: task6-html-app
  template:
    metadata:
      labels:
        app: task6-html-app
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: html
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
